#' Descargar datos de Modelo de Expansion
#' 
#' Descargas datos para modelar de sql. 
#'
#' @param con conexion abierta de RODBC
#' @param version version de descarga
#' @export
t_datos_modelo <- function(con, version){
if(version == 1){
q <- "SELECT * FROM 
(SELECT 
a.AGEB_FOLIO, 
a.LLAVEGEO, 
sum(cast(POBTOT as FLOAT)) as POBLACION
FROM bt_censoageb a
GROUP BY a.AGEB_FOLIO, a.LLAVEGEO)sq1
	LEFT JOIN (SELECT AGEB_FOLIO, ZONA, 
					ZONA_AGRUPADA, MACRO_ZONA FROM dim_zonastopaz)b on b.AGEB_FOLIO = sq1.AGEB_FOLIO
	LEFT JOIN (SELECT LLAVEGEO, CLUSTER_ID, CLUSTER FROM m_clusters)c on c.LLAVEGEO = sq1.LLAVEGEO
	LEFT JOIN (SELECT AGEB_FOLIO, CERCANIA, CENTRALIDAD_PODER, 
					CERCANIA_PROM, CERCANIA_REL, N2, N3, CLUSTER_AGEB, ES_SOLO 
					FROM m_conectividad)d on d.AGEB_FOLIO = sq1.AGEB_FOLIO
	LEFT JOIN (SELECT AGEB_FOLIO, AM_GRAPROES, AM_PERSXHOGAR, AM_AUTOS, AM_EDOCIVIL 
					FROM m_alumnomodelo)e on e.AGEB_FOLIO = sq1.AGEB_FOLIO
	LEFT JOIN (SELECT AGEB_FOLIO, TASA_EST, CRIMENES, TENDENCIA FROM m_crimen)f on f.AGEB_FOLIO = sq1.AGEB_FOLIO
	LEFT JOIN (SELECT AGEB_FOLIO, 
					COB_NET_PRIM, COB_NET_SEC, COB_NET_PREP, COB_NET_PROF, 
					REZ_TOTAL_ADULTO, REZ_PREPA_ADULTO, 
					ESCOLARIDAD, PEA, CATOLICOS, CENS_PERSXHOGAR, 
					CENS_AUTO, CENS_PC, 
					EDAD_EDU, EDAD_EDU_PROF, EDAD_EDUF_PREPA, EDAD_EDUF_PROF, 
					P_EDAD_EDU, P_EDAD_EDU_PROF, P_EDAD_EDUF_PREPA, P_EDAD_EDUF_PROF,
					HACINAMIENTO, DENSIDAD, GEN_REZ_PREPA, GEN_PART_PEA, MIGRACION, 
					C_TEORICO, C_PROM
					FROM m_demografia)g on g.AGEB_FOLIO = sq1.AGEB_FOLIO
	LEFT JOIN (SELECT LLAVEGEO, HH_UE_2014, LQ_EMP_2014_11, LQ_EMP_2014_21
					,LQ_EMP_2014_22, LQ_EMP_2014_23, LQ_EMP_2014_43, LQ_EMP_2014_46
					,LQ_EMP_2014_51, LQ_EMP_2014_52, LQ_EMP_2014_53, LQ_EMP_2014_54
					,LQ_EMP_2014_55, LQ_EMP_2014_56, LQ_EMP_2014_61, LQ_EMP_2014_62
					,LQ_EMP_2014_71, LQ_EMP_2014_72, LQ_EMP_2014_81, LQ_EMP_2014_SC, EST_MODELO 
				FROM m_empleadores)h on h.LLAVEGEO = sq1.LLAVEGEO
	LEFT JOIN (SELECT LLAVEGEO, LQ_EMP_2014_OTROS, LQ_ING_2014_OTROS,
					 LQ_EMP_2014_PRIMARIA, LQ_ING_2014_PRIMARIA,
					 LQ_EMP_2014_SECUNDARIA, LQ_ING_2014_SECUNDARIA, 
					 LQ_EMP_2014_TERCIARIA, LQ_ING_2014_TERCIARIA
					 FROM dbo.m_lq)i on i.LLAVEGEO = sq1.LLAVEGEO
	LEFT JOIN (SELECT LLAVEGEO, TMR_SEC, TMR_PREP, TMR_PROF,
					TA_PREP, TA_PRO,
					L_ADMINISTRACION, L_ARQUITECTURA_Y_CONSTRUCCION,
					L_CIENCIAS_DE_LA_INFORMACION, L_CIENCIAS_SOCIALES_Y_ESTUDIOS_DEL_COMPORTAMIENTO,
					L_DERECHO, L_HUMANIDADES, L_INGENIERIA_INDUSTRIAL__MECANICA_Y_ELECTRICA,
					L_MANUFACTURAS_Y_PROCESOS, L_NEGOCIOS, L_SALUD, C_ADMINISTRACION, 
					C_ARQUITECTURA_Y_CONSTRUCCION, C_CIENCIAS_DE_LA_INFORMACION,
					C_CIENCIAS_SOCIALES_Y_ESTUDIOS_DEL_COMPORTAMIENTO, C_DERECHO,
					C_HUMANIDADES, C_INGENIERIA_INDUSTRIAL__MECANICA_Y_ELECTRICA, 
					C_MANUFACTURAS_Y_PROCESOS, C_NEGOCIOS, C_SALUD
				FROM dbo.m_oferta)j on j.LLAVEGEO = sq1.LLAVEGEO"
}

d <- RODBC::sqlQuery(channel = con, query = q)
d
}
